var myObj, x;
myObj = {
  'cascade':[
    'Chomp Through the Rocks',
    'Behind the Waterfall',
    'On Top of the Rubble',
    'Treasure of the Waterfall Basin',
    'Above a High Cliff',
    'Across the Floating Isle',
    'Cascade Kingdom Timer Challenge 1',
    'Cascade Kingdom Timer Challenge 2',
    'Good Morning, Captain Toad!',
    '<font color="blue">Dinosaur Nest: Big Cleanup!</font>',
    '<font color="blue">Dinosaur Nest: Running Wild!</font>',
    '<font color="blue">Nice Shot with the Chain Chomp!</font>',
    '<font color="blue">Very Nice Shot with the Chain Chomp!</font>',
    '<font color="blue">Past the Chasm Lifts</font>',
    '<font color="blue">Hidden Chasm Passage</font>',
    '<font color="red">Our First Power Moon</font>',
    '<font color="red">Multi Moon Atop the Falls (+3)</font>'
  ],
  'sand':[
    'Overlooking the Desert Town',
    'Alcove in the Ruins',
    'On the Leaning Pillar',
    'Hidden Room in the Flowing Sands',
    'Secret of the Mural',
    'On Top of the Stone Archway',
    'From a Crate in the Ruins',
    'On the Lone Pillar',
    'Where the Birds Gather',
    'Top of a Dune',
    'Lost in the Luggage',
    'Inside a Block Is a Hard Place',
    'Bird Traveling the Desert',
    'The Treasure of Jaxi Ruins',
    'Taking Notes: Jump on the Palm',
    'Wandering Cactus',
    'Sand Quiz: Wonderful!',
    '<font color="purple">Shopping in Tostarena</font>',
    'Employees Only',
    '<font color="purple">Sand Kingdom Slots</font>',
    'Walking the Desert!',
    "Sphynx's Treasure Vault",
    'A Rumble from the Sandy Floor',
    '<font color="blue">The Invisible Maze</font>',
    '<font color="blue">Skull Sign in the Transparent Maze</font>',
    '<font color="blue">Jaxi Driver</font>',
    '<font color="blue">Jaxi Stunt Driving</font>'
  ],
  'lake':[
    'Dorrie-Back Rider',
    'Cheep Cheep Crossing',
    'End of the Hidden Passage',
    "What's in the Box?",
    'On the Lakeshore',
    'From the Broken Pillar',
    'Treasure in the Spiky Waterway',
    'Moon Shards in the Lake',
    'Taking Notes: Dive and Swim',
    'Taking Notes: In the Cliffside',
    'Our Secret Little Room',
    "Let's Go Swimming, Captain Toad!",
    '<font color="purple">Shopping in Lake Lamode</font>',
    '<font color="blue">Unzip the Chasm</font>',
    '<font color="blue">Super-Secret Zipper</font>',
    '<font color="blue">Jump, Grab, Cling, and Climb</font>',
    '<font color="blue">Jump, Grab, and Climb Some More</font>',
    '<font color="red">Broodals Over the Lake (+3)</font>'
  ],
  'wooded':[
    'Rolling Rock in the Woods',
    'Caught Hopping in the Forest!',
    'Atop the Tall Tree',
    'Tucked Away Inside the Tunnel',
    "The Nut 'Round The Corner",
    'Climb the Cliff to Get the Nut',
    'The Nut in the Red Maze',
    'The Nut at the Dead End',
    'Cracked Nut on a Crumbling Tower',
    'Fire in the Cave',
    '<font color="purple">Shopping in Steam Gardens</font>',
    '<font color="blue">Nut Planted in the Tower</font>',
    '<font color="blue">Stretching Your Legs</font>',
    '<font color="blue">Flooding Pipeway</font>',
    '<font color="blue">Flooding Pipeway Ceiling Secret</font>',
    '<font color="red">Road to Sky Garden</font>',
    '<font color="red">Flower Thieves to Sky Garden (+3)</font>'
  ],
  'lost':[
    'Atop a Propeller Pillar',
    "Below the Cliff's Edge",
    'Inside the Stone Cage',
    'On a Tree in the Swamp',
    'Over the Fuzzies, Above the Swamp',
    'Avoiding Fuzzies Inside the Wall',
    'Inside the Rising Stone Pillar',
    'Enjoying the View of Forgotten Isle',
    'On the Mountain Road',
    "A Propeller Pillar's Secret",
    'Wrecked Rock Block',
    "A Butterfly's Treasure",
    'Cave Gardening',
    'Moon Shards in the Jungle',
    'Peeking Out from Under the Bridge',
    "Twist 'n' Turn-Up Treasure",
    'Soaring Over Forgotten Isle!',
    'The Caged Gold',
    'Get Some Rest, Captain Toad!',
    '<font color="purple">Shopping on Forgotten Isle</font>'
  ],
  'metro':[
    'Drummer on Board!',
    'Guitarist on Board!',
    'Bassist on Board!',
    'Trumpeter on Board!',
    'Inside an Iron Girder',
    'Swaying in the Breeze',
    'Girder Sandwich',
    'Glittering Above the Pool',
    'Dizzying Heights',
    'Secret Girder Tunnel!',
    'Who Piled Garbage on This?',
    'Hidden in the Scrap',
    'Left at the Cafe?',
    'How Do They Take Out the Trash?',
    "How You Doin', Captain Toad?",
    'Bench Friends',
    '<font color="purple">Shopping in New Donk City</font>',
    '<font color="purple">Metro Kingdom Slots</font>',
    'Remotely Captured Car',
    '<font color="blue">RC Car Pro!</font>',
    '<font color="blue">Taking Notes: In the Private Room</font>',
    '<font color="blue">City Hall Lost & Found</font>',
    '<font color="blue">Pushing Through the Crowd</font>',
    '<font color="blue">High Over the Crowd</font>',
    '<font color="blue">Inside the Rotating Maze</font>',
    '<font color="blue">Outside the Rotating Maze</font>',
    '<font color="blue">Hanging from a High-Rise</font>',
    '<font color="blue">Vaulting up a High-Rise</font>',
    '<font color="blue">Bullet Billding</font>',
    "<font color='blue'>One Man's Trash...</font>",
    '<font color="blue">Motor Scooter: Escape!</font>',
    '<font color="blue">Big Jump: Escape!</font>',
    "<font color='red'>New Donk City's Pest Problem (+3)</font>"
  ],
  'snow':[
    'The Icicle Barrier',
    'The Ice Wall Barrier',
    'The Gusty Barrier',
    'Entrance to Shiveria',
    'Behind Snowy Mountain',
    'Shining in the Snow in Town',
    'Atop a Blustery Arch',
    'The Shiverian Treasure Chest',
    'Treasure in the Ice Wall',
    'Ice-Dodging Goomba Stack',
    'Captain Toad is Chilly!',
    '<font color="purple">Shopping in Shiveria</font>'
  ],
  'seaside':[
    'The Stone Pillar Seal',
    'The Lighthouse Seal',
    'The Hot Spring Seal',
    'The Seal Above the Canyon',
    'On the Cliff Overlooking the Beach',
    'Ride the Jetstream',
    "Shh! It's a Shortcut",
    'Gap in the Ocean Trench',
    'Merci, Dorrie!',
    'Under a Dangerous Ceiling',
    'What the Waves Left Behind',
    'The Back Canyon: Excavate!',
    'Bubblaine Northern Reaches',
    'Glass Palace Treasure Chest',
    'Treasure Trap Hidden in the Inlet',
    'Taking Notes: Ocean Surface Dash',
    'Good Job, Captain Toad!',
    'Ocean Quiz: Good!',
    '<font color="purple">Shopping in Bubblaine</font>',
    '<font color="blue">Looking Back in the Dark Waterway</font>',
    "<font color='blue'>The Sphynx's Underwater Vault</font>",
    '<font color="blue">A Rumble on the Seaside Floor</font>',
    '<font color="blue">Wading in the Cloud Sea</font>',
    '<font color="blue">Sunken Treasure in the Cloud Sea</font>',
    '<font color="blue">Hurry and Stretch</font>',
    '<font color="blue">Stretch on the Side Path</font>'
  ],
  'luncheon':[
    'Piled on the Salt',
    "Lurking in the Pillar's Shadow",
    'Atop the Jutting Crag',
    'Is This an Ingredient Too?!',
    'Atop a Column in a Row',
    'Surrounded by Tall Mountains',
    'Island of Salt Floating in the Lava',
    'Overlooking a Bunch of Ingredients',
    'Light the Lantern on the Small Island',
    'Golden Turnip Recipe 1',
    'Golden Turnip Recipe 2',
    'Luncheon Kingdom Timer Challenge 1',
    'Beneath the Rolling Vegetables',
    'All the Cracks Are Fixed',
    'Taking Notes: Swimming in Magma',
    'Love Above the Lava',
    '<font color="purple">Shopping in Mount Volbono</font>',
    '<font color="purple">Luncheon Kingdom Slots</font>',
    '<font color="blue">Magma Swamp: Floating and Sinking</font>',
    '<font color="blue">Corner of the Magma Swamp</font>',
    '<font color="blue">Magma Narrow Path</font>',
    '<font color="blue">Crossing to the Magma</font>',
    "<font color='blue'>Fork Flickin' to the Summit</font>",
    "<font color='blue'>Fork Flickin' Detour</font>",
    "<font color='red'>The Broodals Are After Some Cookin'</font>",
    '<font color="red">Under the Cheese Rocks</font>',
    '<font color="red">Big Pot on the Volcano: Dive In! (+3)</font>'
  ],
  'ruined':[
    "<font color='red'>Battle with the Lord of Lightning (+3)</font>"
  ],
  'bowser':[
    'Behind the Big Wall',
    'Treasure Inside the Turret',
    'From the Side Above the Castle Gate',
    'Sunken Treasure in the Moat',
    'Caught on the Iron Fence',
    "On the Giant Bowser Statue's Nose",
    'Inside a Block in the Castle',
    'Taking Notes: Between Spinies',
    'Stack Up Above the Wall',
    'Hidden Corridor Under the Floor',
    'Poking Your Nose in the Plaster Wall',
    'Poking the Turret Wall',
    'Poking Your Nose by the Great Gate',
    'Jizo All in a Row',
    'Underground Jizo',
    'Found Behind Bars!',
    'Good to See You, Captain Toad!',
    "<font color='purple'>Shopping at Bowser's Castle</font>",
    "<font color='red'>Infiltrate Bowser's Castle</font>",
    '<font color="red">Smart Bombing</font>',
    '<font color="red">Big Broodal Battle</font>',
    "<font color='red'>Showdown at Bowser's Castle (+3)</font>"
  ]};
