var myObj, x;
myObj = {
  'cascade':[
    'Chomp Through the Rocks',
    'Behind the Waterfall',
    'On Top of the Rubble',
    'Treasure of the Waterfall Basin',
    'Above a High Cliff',
    'Across the Floating Isle',
    'Cascade Kingdom Timer Challenge 1',
    'Cascade Kingdom Timer Challenge 2',
    'Good Morning, Captain Toad!',
    'Dinosaur Nest: Big Cleanup!',
    'Dinosaur Nest: Running Wild!',
    'Nice Shot with the Chain Chomp!',
    'Very Nice Shot with the Chain Chomp!',
    'Past the Chasm Lifts',
    'Hidden Chasm Passage',
    'Our First Power Moon',
    'Multi Moon Atop the Falls (+3)'
  ],
  'sand':[
    'Atop the Highest Tower',
    'Overlooking the Desert Town',
    'Alcove in the Ruins',
    'On the Leaning Pillar',
    'Hidden Room in the Flowing Sands',
    'Secret of the Mural',
    'On Top of the Stone Archway',
    'From a Crate in the Ruins',
    'On the Lone Pillar',
    'Where the Birds Gather',
    'Top of a Dune',
    'Lost in the Luggage',
    'Inside a Block Is a Hard Place',
    'Bird Traveling the Desert',
    'The Treasure of Jaxi Ruins',
    'Taking Notes: Jump on the Palm',
    'Among the Five Cactuses',
    'Wandering Cactus',
    'Sand Quiz: Wonderful!',
    'Shopping in Tostarena',
    'Employees Only',
    'Sand Kingdom Slots',
    'Walking the Desert!',
    'Ice Cave Treasure',
    "Sphynx's Treasure Vault",
    'A Rumble from the Sandy Floor',
    'The Invisible Maze',
    'Skull Sign in the Transparent Maze',
    'The Bullet Bill Maze: Break Through!',
    'The Bullet Bill Maze: Side Path',
    'Jaxi Driver',
    'Jaxi Stunt Driving'
  ],
  'lake':[
    'Dorrie-Back Rider',
    'Cheep Cheep Crossing',
    'End of the Hidden Passage',
    "What's in the Box?",
    'On the Lakeshore',
    'From the Broken Pillar',
    'Treasure in the Spiky Waterway',
    'Moon Shards in the Lake',
    'Taking Notes: Dive and Swim',
    'Taking Notes: In the Cliffside',
    'Our Secret Little Room',
    "Let's Go Swimming, Captain Toad!",
    'Shopping in Lake Lamode',
    'I Feel Underdressed',
    'Super-Secret Zipper',
    'Jump, Grab, Cling, and Climb',
    'Jump, Grab, and Climb Some More',
    'Broodals Over the Lake (+3)'
  ],
  'wooded':[
    'Rolling Rock in the Woods',
    'Caught Hopping in the Forest!',
    'Atop the Tall Tree',
    'Tucked Away Inside the Tunnel',
    "The Nut 'Round The Corner",
    'Climb the Cliff to Get the Nut',
    'The Nut in the Red Maze',
    'The Nut at the Dead End',
    'Cracked Nut on a Crumbling Tower',
    'Fire in the Cave',
    'Shopping in Steam Gardens',
    'Nut Planted in the Tower',
    'Stretching Your Legs',
    'Flooding Pipeway',
    'Flooding Pipeway Ceiling Secret',
    'Road to Sky Garden',
    'Flower Thieves to Sky Garden (+3)'
  ],
  'lost':[
    'Atop a Propeller Pillar',
    "Below the Cliff's Edge",
    'Inside the Stone Cage',
    'On a Tree in the Swamp',
    'Over the Fuzzies, Above the Swamp',
    'Avoiding Fuzzies Inside the Wall',
    'Inside the Rising Stone Pillar',
    'Enjoying the View of Forgotten Isle',
    'On the Mountain Road',
    "A Propeller Pillar's Secret",
    'Wrecked Rock Block',
    "A Butterfly's Treasure",
    'Cave Gardening',
    'Moon Shards in the Jungle',
    'Peeking Out from Under the Bridge',
    "Twist 'n' Turn-Up Treasure",
    'Soaring Over Forgotten Isle!',
    'The Caged Gold',
    'Get Some Rest, Captain Toad!',
    'Shopping on Forgotten Isle'
  ],
  'metro':[
    'Drummer on Board!',
    'Guitarist on Board!',
    'Bassist on Board!',
    'Trumpeter on Board!',
    'Inside an Iron Girder',
    'Swaying in the Breeze',
    'Girder Sandwich',
    'Glittering Above the Pool',
    'Dizzying Heights',
    'Secret Girder Tunnel!',
    'Who Piled Garbage on This?',
    'Hidden in the Scrap',
    'Left at the Cafe?',
    'How Do They Take Out the Trash?',
    "How You Doin', Captain Toad?",
    'Free Parking: Rooftop Hop',
    'Bench Friends',
    'Shopping in New Donk City',
    'Metro Kingdom Slots',
    'Remotely Captured Car',
    'RC Car Pro!',
    'Taking Notes: In the Private Room',
    'City Hall Lost & Found',
    'Pushing Through the Crowd',
    'High Over the Crowd',
    'Moon Shards Under Siege',
    'Sharpshooting Under Siege',
    'Inside the Rotating Maze',
    'Outside the Rotating Maze',
    'Hanging from a High-Rise',
    'Vaulting up a High-Rise',
    'Bullet Billding',
    "One Man's Trash...",
    'Motor Scooter: Escape!',
    'Big Jump: Escape!',
    "New Donk City's Pest Problem (+3)"
  ],
  'snow':[
    'The Icicle Barrier',
    'The Ice Wall Barrier',
    'The Gusty Barrier',
    'The Snowy Mountain Barrier',
    'Entrance to Shiveria',
    'Behind Snowy Mountain',
    'Shining in the Snow in Town',
    'Atop a Blustery Arch',
    'The Shiverian Treasure Chest',
    'Treasure in the Ice Wall',
    'Ice-Dodging Goomba Stack',
    'Captain Toad is Chilly!',
    'Shopping in Shiveria'
  ],
  'seaside':[
    'The Stone Pillar Seal',
    'The Lighthouse Seal',
    'The Hot Spring Seal',
    'The Seal Above the Canyon',
    'On the Cliff Overlooking the Beach',
    'Ride the Jetstream',
    'Ocean-Bottom Maze: Treasure',
    'Ocean-Bottom Maze: Hidden Room',
    'Underwater Highway Tunnel',
    "Shh! It's a Shortcut",
    'Gap in the Ocean Trench',
    'Slip Through the Nesting Spot',
    'Merci, Dorrie!',
    'Under a Dangerous Ceiling',
    'What the Waves Left Behind',
    'The Back Canyon: Excavate!',
    'Bubblaine Northern Reaches',
    'Wriggling on the Sandy Bottom',
    'Glass Palace Treasure Chest',
    'Treasure Trap Hidden in the Inlet',
    'Seaside Kingdom Timer Challenge 1',
    'Moon Shards in the Sea',
    'Taking Notes: Ocean Surface Dash',
    'Love by the Seaside',
    'Good Job, Captain Toad!',
    'Ocean Quiz: Good!',
    'Shopping in Bubblaine',
    'Looking Back in the Dark Waterway',
    "The Sphynx's Underwater Vault",
    'A Rumble on the Seaside Floor',
    'Wading in the Cloud Sea',
    'Sunken Treasure in the Cloud Sea',
    'Fly Through the Narrow Valley',
    'Treasure Chest in the Narrow Valley',
    'Hurry and Stretch',
    'Stretch on the Side Path'
  ],
  'luncheon':[
    'Piled on the Salt',
    "Lurking in the Pillar's Shadow",
    'Atop the Jutting Crag',
    'Is This an Ingredient Too?!',
    'Atop a Column in a Row',
    'Surrounded by Tall Mountains',
    'Island of Salt Floating in the Lava',
    'Overlooking a Bunch of Ingredients',
    'Light the Lantern on the Small Island',
    'Golden Turnip Recipe 1',
    'Golden Turnip Recipe 2',
    'Golden Turnip Recipe 3',
    'Luncheon Kingdom Timer Challenge 1',
    'Beneath the Rolling Vegetables',
    'All the Cracks Are Fixed',
    'Taking Notes: Swimming in Magma',
    'Love Above the Lava',
    'Shopping in Mount Volbono',
    'Luncheon Kingdom Slots',
    'Magma Swamp: Floating and Sinking',
    'Corner of the Magma Swamp',
    'Magma Narrow Path',
    'Crossing to the Magma',
    "Fork Flickin' to the Summit",
    "Fork Flickin' Detour",
    "Excavate 'n' Search the Cheese Rocks",
    'Climb the Cheese Rocks',
    'Spinning Athletics End Goal',
    'Taking Notes: Spinning Atheletics',
    "The Broodals Are After Some Cookin'",
    'Under the Cheese Rocks',
    'Big Pot on the Volcano: Dive In! (+3)'
  ],
  'ruined':[
    "Battle with the Lord of Lightning"
  ],
  'bowser':[
    'Behind the Big Wall',
    'Treasure Inside the Turret',
    'From the Side Above the Castle Gate',
    'Sunken Treasure in the Moat',
    'Caught on the Iron Fence',
    "On the Giant Bowser Statue's Nose",
    'Inside a Block in the Castle',
    'Exterminate the Ogres!',
    'Taking Notes: Between Spinies',
    'Stack Up Above the Wall',
    'Hidden Corridor Under the Floor',
    'Poking Your Nose in the Plaster Wall',
    'Poking the Turret Wall',
    'Poking Your Nose by the Great Gate',
    'Jizo All in a Row',
    'Underground Jizo',
    'Found Behind Bars!',
    'Good to See You, Captain Toad!',
    "Shopping at Bowser's Castle",
    'Scene of Crossing the Poison Swamp',
    'Taking Notes: In the Folding Screen',
    'Dashing Above the Clouds',
    'Dashing Through the Clouds',
    "Infiltrate Bowser's Castle",
    'Smart Bombing',
    'Big Broodal Battle',
    "Showdown at Bowser's Castle (+3)"
  ]};
