var myObj, x;
myObj = {
  'cascade'/*15*/:[
    'Chomp Through the Rocks',
    'Behind the Waterfall',
    'On Top of the Rubble',
    'Treasure of the Waterfall Basin',
    'Above a High Cliff',
    'Across the Floating Isle',
    'Cascade Kingdom Timer Challenge 1',
    'Cascade Kingdom Timer Challenge 2',
    'Good Morning, Captain Toad!',
    '<font color="blue">Dinosaur Nest: Big Cleanup!</font>',
    '<font color="blue">Dinosaur Nest: Running Wild!</font>',
    '<font color="blue">Nice Shot with the Chain Chomp!</font>',
    '<font color="blue">Very Nice Shot with the Chain Chomp!</font>',
    '<font color="blue">Past the Chasm Lifts</font>',
    '<font color="blue">Hidden Chasm Passage</font>',
    '<font color="red">Our First Power Moon</font>',
    '<font color="red">Multi Moon Atop the Falls (+3)</font>'
  ],
  'sand'/*36*/:[
    'Overlooking the Desert Town',
    'Alcove in the Ruins',
    'On the Leaning Pillar',
    'Hidden Room in the Flowing Sands',
    'Secret of the Mural',
    'Secret of the Inverted Mural'
    'On Top of the Stone Archway',
    'From a Crate in the Ruins',
    'On the Lone Pillar',
    "On the Statue's Tail",
    'Where the Birds Gather',
    'Top of a Dune',
    'Lost in the Luggage',
    'Bullet Bill Breakthrough'
    'Inside a Block Is a Hard Place',
    'Bird Traveling the Desert',
    'The Treasure of Jaxi Ruins',
    'Taking Notes: Jump on the Palm',
    'Among the Five Cactuses',
    'Wandering Cactus',
    'Sand Quiz: Wonderful!',
    '<font color="purple">Shopping in Tostarena</font>',
    'Employees Only',
    '<font color="purple">Sand Kingdom Slots</font>',
    'Hidden Room in the Inverted Pyramid',
    'Underground Treasure Chest',
    'Goomba Tower Assembly',
    'Ice Cave Treasure',
    "Sphynx's Treasure Vault",
    'A Rumble from the Sandy Floor',
    '<font color="blue">The Invisible Maze</font>',
    '<font color="blue">Skull Sign in the Transparent Maze</font>',
    '<font color="blue">The Bullet Bill Maze: Break Through!</font>',
    '<font color="blue">The Bullet Bill Maze: Side Path</font>',
    '<font color="blue">Jaxi Driver</font>',
    '<font color="blue">Jaxi Stunt Driving</font>',
    '<font color="red">Atop the Highest Tower</font>',
    '<font color="red">Moon Shards In The Sand</font>',
    '<font color="red">Showdown on the Inverted Pyramid</font>',
    '<font color="red">The Hole in the Desert</font>'
  ],
  'lake'/*17*/:[
    'Dorrie-Back Rider',
    'Cheep Cheep Crossing',
    'End of the Hidden Passage',
    "What's in the Box?",
    'On the Lakeshore',
    'From the Broken Pillar',
    'Treasure in the Spiky Waterway',
    'Moon Shards in the Lake',
    'Taking Notes: Dive and Swim',
    'Taking Notes: In the Cliffside',
    'Our Secret Little Room',
    "Let's Go Swimming, Captain Toad!",
    '<font color="purple">Shopping in Lake Lamode</font>',
    '<font color="blue">Unzip the Chasm</font>',
    '<font color="blue">Super-Secret Zipper</font>',
    '<font color="blue">Jump, Grab, Cling, and Climb</font>',
    '<font color="blue">Jump, Grab, and Climb Some More</font>',
    '<font color="red">Broodals Over the Lake (+3)</font>'
  ],
  'wooded'/*28*/:[
    'Behind the Rock Wall',
    'Back Way Up the Mountain',
    'Rolling Rock in the Woods',
    'Caught Hopping in the Forest!',
    'Thanks for the Charge!',
    'Atop the Tall Tree',
    'Tucked Away Inside the Tunnel',
    "Over the Cliff's Edge",
    "The Nut 'Round The Corner",
    'Climb the Cliff to Get the Nut',
    'The Nut in the Red Maze',
    'The Nut at the Dead End',
    'Cracked Nut on a Crumbling Tower',
    'The Nut that Grew on the Tall Fence',
    'Fire in the Cave',
    'Love in the Forest Ruins',
    '<font color="purple">Shopping in Steam Gardens</font>',
    '<font color="blue">Nut Planted in the Tower</font>',
    '<font color="blue">Stretching Your Legs</font>',
    'Spinning-Platforms Treasure',
    '<font color="blue">Flooding Pipeway</font>',
    '<font color="blue">Flooding Pipeway Ceiling Secret</font>',
    'Wandering in the Fog',
    'Nut Hidden in the Fog',
    'Flower Road Run',
    'Flower Road Reach',
    'Elevator Escalation',
    'Elevator Blind Spot',
    '<font color="red">Road to Sky Garden</font>',
    '<font color="red">Flower Thieves to Sky Garden (+3)</font>',
    '<font color="red">Path to the Secret Flower Field</font>',
    '<font color="red">Defend the Secret Flower Field! (+3)</font>'
  ],
  'lost'/*20*/:[
    'Atop a Propeller Pillar',
    "Below the Cliff's Edge",
    'Inside the Stone Cage',
    'On a Tree in the Swamp',
    'Over the Fuzzies, Above the Swamp',
    'Avoiding Fuzzies Inside the Wall',
    'Inside the Rising Stone Pillar',
    'Enjoying the View of Forgotten Isle',
    'On the Mountain Road',
    "A Propeller Pillar's Secret",
    'Wrecked Rock Block',
    "A Butterfly's Treasure",
    'Cave Gardening',
    'Moon Shards in the Jungle',
    'Peeking Out from Under the Bridge',
    "Twist 'n' Turn-Up Treasure",
    'Soaring Over Forgotten Isle!',
    'The Caged Gold',
    'Get Some Rest, Captain Toad!',
    '<font color="purple">Shopping on Forgotten Isle</font>'
  ],
  'metro'/*33*/:[
    'Inside an Iron Girder',
    'Swaying in the Breeze',
    'Girder Sandwich',
    'Glittering Above the Pool',
    'Dizzying Heights',
    'Secret Girder Tunnel!',
    'Who Piled Garbage on This?',
    'Hidden in the Scrap',
    'Left at the Cafe?',
    'How Do They Take Out the Trash?',
    "How You Doin', Captain Toad?",
    'Free Parking: Rooftop Hop',
    'Bench Friends',
    '<font color="purple">Shopping in New Donk City</font>',
    '<font color="purple">Metro Kingdom Slots</font>',
    'Remotely Captured Car',
    '<font color="blue">RC Car Pro!</font>',
    '<font color="blue">Taking Notes: In the Private Room</font>',
    '<font color="blue">City Hall Lost & Found</font>',
    'Sewer Treasure',
    'Celebrating in the Streets!',
    '<font color="blue">Pushing Through the Crowd</font>',
    '<font color="blue">High Over the Crowd</font>',
    '<font color="blue">Moon Shards Under Siege</font>',
    '<font color="blue">Sharpshooting Under Siege</font>',
    '<font color="blue">Inside the Rotating Maze</font>',
    '<font color="blue">Outside the Rotating Maze</font>',
    '<font color="blue">Hanging from a High-Rise</font>',
    '<font color="blue">Vaulting up a High-Rise</font>',
    '<font color="blue">Bullet Billding</font>',
    "<font color='blue'>One Man's Trash...</font>",
    '<font color="blue">Motor Scooter: Escape!</font>',
    '<font color="blue">Big Jump: Escape!</font>',
    "<font color='red'>New Donk City's Pest Problem (+3)</font>",
    '<font color="red">Drummer on Board!</font>',
    '<font color="red">Guitarist on Board!</font>',
    '<font color="red">Bassist on Board!</font>',
    '<font color="red">Trumpeter on Board!</font>',
    "<font color='red'>Powering Up the Station</font>",
    "<font color='red'>A Traditional Festival (+3)</font>",
  ],
  'snow'/*9*/:[
    'Entrance to Shiveria',
    'Behind Snowy Mountain',
    'Shining in the Snow in Town',
    'Atop a Blustery Arch',
    'The Shiverian Treasure Chest',
    'Treasure in the Ice Wall',
    'Ice-Dodging Goomba Stack',
    'Captain Toad is Chilly!',
    '<font color="purple">Shopping in Shiveria</font>',
    '<font color="red">The Icicle Barrier</font>',
    '<font color="red">The Ice Wall Barrier</font>',
    '<font color="red">The Gusty Barrier</font>',
    '<font color="red">The Snowy Mountain Barrier</font>',
    '<font color="red">The Bound Bowl Grand Prix</font>'
  ],
  'seaside'/*32*/:[
    'On the Cliff Overlooking the Beach',
    'Ride the Jetstream',
    'Ocean-Bottom Maze: Treasure',
    'Ocean-Bottom Maze: Hidden Room',
    'Underwater Highway Tunnel',
    "Shh! It's a Shortcut",
    'Gap in the Ocean Trench',
    'Slip Through the Nesting Spot',
    'Merci, Dorrie!',
    'Under a Dangerous Ceiling',
    'What the Waves Left Behind',
    'The Back Canyon: Excavate!',
    'Bubblaine Northern Reaches',
    'Wriggling on the Sandy Bottom',
    'Glass Palace Treasure Chest',
    'Treasure Trap Hidden in the Inlet',
    'Seaside Kingdom Timer Challenge 1',
    'Moon Shards in the Sea',
    'Taking Notes: Ocean Surface Dash',
    'Love by the Seaside',
    'Good Job, Captain Toad!',
    'Ocean Quiz: Good!',
    '<font color="purple">Shopping in Bubblaine</font>',
    'Looking Back in the Dark Waterway',
    "<font color='blue'>The Sphynx's Underwater Vault</font>",
    '<font color="blue">A Rumble on the Seaside Floor</font>',
    '<font color="blue">Wading in the Cloud Sea</font>',
    '<font color="blue">Sunken Treasure in the Cloud Sea</font>',
    '<font color="blue">Fly Through the Narrow Valley</font>',
    '<font color="blue">Treasure Chest in the Narrow Valley</font>',
    '<font color="blue">Hurry and Stretch</font>',
    '<font color="blue">Stretch on the Side Path</font>',
    '<font color="red">The Stone Pillar Seal</font>',
    '<font color="red">The Lighthouse Seal</font>',
    '<font color="red">The Hot Spring Seal</font>',
    '<font color="red">The Seal Above the Canyon</font>',
    '<font color="red">The Glass Is Half Full!</font>'
  ],
  'luncheon'/*36*/:[
    'Piled on the Salt',
    "Lurking in the Pillar's Shadow",
    'Atop the Jutting Crag',
    'Is This an Ingredient Too?!',
    'Atop a Column in a Row',
    'Surrounded by Tall Mountains',
    'Island of Salt Floating in the Lava',
    'Overlooking a Bunch of Ingredients',
    'Light the Lantern on the Small Island',
    'Golden Turnip Recipe 1',
    'Golden Turnip Recipe 2',
    'Golden Turnip Recipe 3',
    'Luncheon Kingdom Timer Challenge 1',
    'Luncheon Kingdom Timer Challenge 2',
    'Beneath the Rolling Vegetables',
    'All the Cracks Are Fixed',
    'Taking Notes: Swimming in Magma',
    'Love Above the Lava',
    '<font color="purple">Shopping in Mount Volbono</font>',
    '<font color="purple">Luncheon Kingdom Slots</font>',
    'Alcove Behind the Pillars of Magma',
    'Treasure Beneath the Cheese Rocks',
    'Light the Two Flames',
    'Light the Far-Off Lanterns',
    'Bon Appetit, Captain Toad!',
    'The Treasure Chest in the Veggies',
    '<font color="blue">Magma Swamp: Floating and Sinking</font>',
    '<font color="blue">Corner of the Magma Swamp</font>',
    '<font color="blue">Magma Narrow Path</font>',
    '<font color="blue">Crossing to the Magma</font>',
    "<font color='blue'>Fork Flickin' to the Summit</font>",
    "<font color='blue'>Fork Flickin' Detour</font>",
    "<font color='blue'>Excavate 'n' Search the Cheese Rocks</font>",
    '<font color="blue">Climb the Cheese Rocks</font>',
    '<font color="blue">Spinning Athletics End Goal</font>',
    '<font color="blue">Taking Notes: Spinning Atheletics</font>',
    "<font color='red'>The Broodals Are After Some Cookin'</font>",
    '<font color="red">Under the Cheese Rocks</font>',
    '<font color="red">Big Pot on the Volcano: Dive In! (+3)</font>',
    '<font color="red">Climb Up the Cascading Magma</font>',
    '<font color="red">Cookatiel Showdown!</font>',
  ],
  'ruined':[
    "<font color='red'>Battle with the Lord of Lightning (+3)</font>"
  ],
  'bowser'/*18*/:[
    'Behind the Big Wall',
    'Treasure Inside the Turret',
    'From the Side Above the Castle Gate',
    'Sunken Treasure in the Moat',
    'Caught on the Iron Fence',
    "On the Giant Bowser Statue's Nose",
    'Inside a Block in the Castle',
    'Exterminate the Ogres!',
    'Taking Notes: Between Spinies',
    'Stack Up Above the Wall',
    'Hidden Corridor Under the Floor',
    'Poking Your Nose in the Plaster Wall',
    'Poking the Turret Wall',
    'Poking Your Nose by the Great Gate',
    'Jizo All in a Row',
    'Underground Jizo',
    'Found Behind Bars!',
    'Good to See You, Captain Toad!',
    "<font color='purple'>Shopping at Bowser's Castle</font>",
    '<font color="blue">Dashing Above the Clouds</font>',
    '<font color="blue">Dashing Through the Clouds</font>',
    "<font color='red'>Infiltrate Bowser's Castle</font>",
    '<font color="red">Smart Bombing</font>',
    '<font color="red">Big Broodal Battle</font>',
    "<font color='red'>Showdown at Bowser's Castle (+3)</font>"
  ]};
